### ISSUE TITLE
redirection https

### ISSUE THREAD

**Issue by akakeronos** [okfnfr/dada-core#20]
Ajouter une redirection de http vers https

**Comment by laurentS** [comment]
Pour moi, http://madada.fr/ redirige sur https://madada.fr/
Est-ce que tu as une url en particulier qui pose problème?

**Comment by akakeronos** [comment]
Pour moi aussi à l'instant mais quand j'ai essayé ce matin cela ne fonctionnait pas. Apparemment pour d'autrs personnes aussi car le problème a été rapporté sur Twitter. Peut-être à cause de nombre problème de crédit d'hébergement :)

**Comment by laurentS** [comment]
Le problème a été rapporté encore une fois aujourd'hui, je rouvre. J'ai demandé plus de détails pour pouvoir creuser l'origine.

**Comment by laurentS** [comment]
D'après https://en.internet.nl/site/madada.fr il semblerait qu'il manque la redirection vers httpS quand on accède au serveur via IPv6. Je m'en occupe.

**Comment by laurentS** [comment]
Il manquait effectivement une configuration pour que nginx écoute sur l'IPv6 en plus de l'IPv4. C'est reglé, et tout le traffic HTTP est aussi renvoyé sur HTTPS.

Il reste encore le fait que `http|https://<ipserveur>` ne redirige pas vers le site, mais la page d'accueil de nginx. Pas le temps de regler ça aujourd'hui, mais j'ouvre un ticket pour mémoire.
