### ISSUE TITLE
certifiat ssl expiré ?

### ISSUE THREAD

**Issue by akakeronos** [okfnfr/dada-core#8]
En me connectant sur le site à l'instant j'ai eu une erreur de validité du certificat ssl
"Le certificat de madada.fr a expiré le 21/10/2019."

**Comment by pzwsk** [comment]
De même, pas de com avant que ça soit réglé svp.

Le lun. 21 oct. 2019 à 9:30 PM, Pascal Romain <notifications@github.com> a
écrit :

**Comment by laurentS** [comment]
C'est reglé pour les 3 mois à venir. On laisse ce ticket ouvert jusqu'à
ce que j'ai mis un cronjob en place pour renouveler automatiquement.

**Comment by laurentS** [comment]
Je ferme ce ticket, mais il est important de suivre la procédure décrite dans [cet autre ticket](https://github.com/okfnfr/dada-core/issues/6#issuecomment-527367993) pour renouveler les certificats sans casser le serveur mail.
