### ISSUE TITLE
demande non visible

### ISSUE THREAD

**Issue by akakeronos** [okfnfr/dada-core#9]
J'ai fait une demande en tant que Pascal
On la voit ici https://madada.fr/demande/composition_socio_professionnell et elle est listée dans le compteur des demandes (actuellement 2 demandes ouvertes) mais on ne la voit pas apparaître dans la liste des demandes en cours

**Comment by pzwsk** [comment]
Ni dans la liste des demandes de l utilisateur.

Le sam. 26 oct. 2019 à 3:04 PM, Pascal Romain <notifications@github.com> a
écrit :

**Comment by akakeronos** [comment]
La seule différence entre les 3 demandes non publiées et celle qui apparaît en ligne c'est l'heure à laquelle elles ont été postées. J'ai fait un tour de toutes les fonctions disponibles depuis l'administration et je n'ai rien trouvé qui puisse expliquer ce problème

**Comment by akakeronos** [comment]
j'ai essayé de reproduire le problème sur l'environnement de test mais je ne peux pas me créer de compte. De plus sur la page d'accueil on voit bien 2 demandes et on peut les consulter dans la liste des demandes
https://dadastaging.okfn.fr/

**Comment by laurentS** [comment]
Je suis en train de regarder aussi. Sur staging, il y'a en fait 3 demandes, donc problème similaire, elles sont toutes faites depuis le même compte, donc je suppose que ce n'est pas lié à un paramètre de l'utilisateur demandeur.

**Comment by laurentS** [comment]
J'ai plus ou moins identifié le problème, il semble qu'il nous manque quelques `cron` jobs que j'ai dû louper pendant l'installation. Une mesure un peu drastique en première approche consiste à redéployer la dernière version du code, ce qui met à jour `xapian`, qui semble être le problème ici.
Je m'occupe de mettre en place les `cron` manquants, et je mets ce ticket à jour une fois que ça fonctionne.

**Comment by laurentS** [comment]
Ca semble être reglé avec le commit ci-dessus. On jette un oeil aux prochaines requêtes, qui devraient apparaitre dans la liste sous 2-3 minutes, le temps pour l'index de se mettre à jour.
Si ce n'est pas le cas, faites moi signe.
